In [42]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [43]:
bp = pd.read_csv('C:/Users/heman/OneDrive/Desktop/Disease Prediction/dataset/blood_pressure.csv')
bp = bp.fillna(0)
bp

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,bmi,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,Blood_Pressure_Abnormality
0,11.28,0.90,34,23,1,1,0,45961,48071,0,2,1,1,1
1,9.75,0.23,54,33,1,0,0,26106,25333,205,3,0,0,0
2,10.79,0.91,70,49,0,0,0,9995,29465,67,2,1,0,1
3,11.00,0.43,71,50,0,0,0,10635,7439,242,1,1,0,0
4,14.17,0.83,52,19,0,0,0,15619,49644,397,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,10.14,0.02,69,26,1,0,1,26118,47568,144,3,1,0,1
1996,11.77,1.00,24,45,1,1,1,2572,8063,0,3,1,1,1
1997,16.91,0.22,18,42,0,0,0,14933,24753,0,2,1,1,1
1998,11.15,0.72,46,45,1,0,1,18157,15275,253,3,0,1,0
1999,11.36,0.09,41,45,0,0,0,20729,30463,230,1,1,0,1

In [44]:

print(bp.dtypes)

Level_of_Hemoglobin              float64
Genetic_Pedigree_Coefficient     float64
Age                                int64
bmi                                int64
Sex                                int64
Pregnancy                          int64
Smoking                            int64
Physical_activity                  int64
salt_content_in_the_diet           int64
alcohol_consumption_per_day        int64
Level_of_Stress                    int64
Chronic_kidney_disease             int64
Adrenal_and_thyroid_disorders      int64
Blood_Pressure_Abnormality         int64
dtype: object

In [45]:
bp.isnull().sum()

Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
bmi                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
Blood_Pressure_Abnormality       0
dtype: int64

In [46]:
bp.describe()

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,bmi,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,Blood_Pressure_Abnormality
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000,2000.000000
mean,11.710035,0.472055,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,220.636500,2.012500,0.5050,0.443500,0.493500
std,2.186701,0.303221,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,157.614106,0.823822,0.5001,0.496922,0.500083
min,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000,0.000000
25%,10.147500,0.200000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,79.000000,1.000000,0.0000,0.000000,0.000000
50%,11.330000,0.470000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,212.500000,2.000000,1.0000,0.000000,0.000000
75%,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000,1.000000
max,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000,1.000000

In [47]:
bp['Blood_Pressure_Abnormality'].value_counts()

Blood_Pressure_Abnormality
0    1013
1     987
Name: count, dtype: int64

In [48]:
bp.groupby('Blood_Pressure_Abnormality').mean()

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,bmi,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
Blood_Pressure_Abnormality,,,,,,,,,,,,,
0,11.409033,0.473722,47.678184,29.615005,0.468904,0.094768,0.503455,24729.517275,24726.965449,224.634748,2.004936,0.293189,0.287266
1,12.018967,0.470344,45.409321,30.560284,0.523810,0.104357,0.515704,25793.159068,25130.474164,216.532928,2.020263,0.722391,0.603850

In [49]:
X = bp.drop(columns='Blood_Pressure_Abnormality', axis=1)
Y = bp['Blood_Pressure_Abnormality']

In [50]:
print(X)

      Level_of_Hemoglobin  Genetic_Pedigree_Coefficient  Age  bmi  Sex  \
0                   11.28                          0.90   34   23    1
1                    9.75                          0.23   54   33    1
2                   10.79                          0.91   70   49    0
3                   11.00                          0.43   71   50    0
4                   14.17                          0.83   52   19    0
...                   ...                           ...  ...  ...  ...
1995                10.14                          0.02   69   26    1
1996                11.77                          1.00   24   45    1
1997                16.91                          0.22   18   42    0
1998                11.15                          0.72   46   45    1
1999                11.36                          0.09   41   45    0

      Pregnancy  Smoking  Physical_activity  salt_content_in_the_diet  \
0             1        0              45961                     48071
1             0        0              26106                     25333
2             0        0               9995                     29465
3             0        0              10635                      7439
4             0        0              15619                     49644
...         ...      ...                ...                       ...
1995          0        1              26118                     47568
1996          1        1               2572                      8063
1997          0        0              14933                     24753
1998          0        1              18157                     15275
1999          0        0              20729                     30463

      alcohol_consumption_per_day  Level_of_Stress  Chronic_kidney_disease  \
0                               0                2                       1
1                             205                3                       0
2                              67                2                       1
3                             242                1                       1
4                             397                2                       0
...                           ...              ...                     ...
1995                          144                3                       1
1996                            0                3                       1
1997                            0                2                       1
1998                          253                3                       0
1999                          230                1                       1

      Adrenal_and_thyroid_disorders
0                                 1
1                                 0
2                                 0
3                                 0
4                                 0
...                             ...
1995                              0
1996                              1
1997                              1
1998                              1
1999                              0

[2000 rows x 13 columns]

In [51]:
print(Y)

0       1
1       0
2       1
3       0
4       1
       ..
1995    1
1996    1
1997    1
1998    0
1999    1
Name: Blood_Pressure_Abnormality, Length: 2000, dtype: int64

In [52]:
scalar = StandardScaler()
Standardized_data = scalar.fit_transform(X)
print(Standardized_data)

[[-0.19670848  1.4116839  -0.73426258 ... -0.01517697  0.9900495
   1.12017473]
 [-0.89656771 -0.79847912  0.435085   ...  1.19898069 -1.0100505
  -0.89271787]
 [-0.4208464   1.44467141  1.37056306 ... -0.01517697  0.9900495
  -0.89271787]
 ...
 [ 2.37859055 -0.83146663 -1.66974063 ... -0.01517697  0.9900495
   1.12017473]
 [-0.25617364  0.81790876 -0.03265403 ...  1.19898069 -1.0100505
   1.12017473]
 [-0.16011453 -1.26030423 -0.32499092 ... -1.22933464  0.9900495
  -0.89271787]]

In [53]:
X = Standardized_data

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(2000, 13) (1600, 13) (400, 13)

In [55]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [56]:
X_train_prediction = classifier.predict(X_train)
trained_accuracy = accuracy_score(X_train_prediction, Y_train)
print(trained_accuracy)

0.7175

In [57]:
X_test_prediction = classifier.predict(X_test)
test_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_accuracy)

0.7025

In [58]:
input_data = (14.17,0.83,52,19,0,0.0,0,15619,49644,397.0,2,0,0)
input_data_as_numpy_array = np.array(input_data)

reshaped_data = input_data_as_numpy_array.reshape(1, -1)

std_data = scalar.transform(reshaped_data)
prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0] == 0):
    print('The person has normal BP')
else:
    print('The person has abnormal BP')

[0]
The person has normal BP

In [59]:
import pickle
filename = '../saved_models/blood_pressure.sav'
pickle.dump(classifier, open(filename,'wb'))
loaded_model = pickle.load(open('../saved_models/blood_pressure.sav', 'rb'))

In [60]:
input_data = (11.69,0.75,43,41,1,1.0,0,38369,32967,206.0,3,1,1)
input_data_as_numpy_array = np.asarray(input_data)

reshaped_data = input_data_as_numpy_array.reshape(1, -1)

std_data = scalar.transform(reshaped_data)
prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0] == 0):
    print('The person has normal BP')
else:
    print('The person has abnormal BP')

[1]
The person has abnormal BP

In [61]:
column_headers = list(bp.columns)
print("The Column Header :", column_headers)

The Column Header : ['Level_of_Hemoglobin', 'Genetic_Pedigree_Coefficient', 'Age', 'bmi', 'Sex', 'Pregnancy', 'Smoking', 'Physical_activity', 'salt_content_in_the_diet', 'alcohol_consumption_per_day', 'Level_of_Stress', 'Chronic_kidney_disease', 'Adrenal_and_thyroid_disorders', 'Blood_Pressure_Abnormality']